Timesheet/Controllers/AttendController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Timesheet.Data;
using Timesheet.Models;
using Timesheet.Repository;

namespace Timesheet.Controllers
{
    [Authorize(Roles = "admin")]
    public class AttendController : Controller
    {
        readonly UserManager<ApplicationUser> _userManager;
        readonly IActivityRepository _activityRepository;
        readonly ILeaveRequestRepository _leaveRequestRepository;
        readonly IAttendanceReportRepository _attendanceReportRepository;
        readonly IUserRepository _userRepository;
        readonly ILeaveBalanceConfigRepository _leaveBalanceConfigRepository;
        readonly ITimiosStaffRepository _timiosStaffRepository;

        public AttendController(UserManager<ApplicationUser> userManager, IActivityRepository activityRepository,
                                ILeaveRequestRepository leaveRequestRepository, IAttendanceReportRepository attendanceReportRepository,
                                IUserRepository userRepository, ILeaveBalanceConfigRepository leaveBalanceConfigRepository, 
                                ITimiosStaffRepository timiosStaffRepository)
        {
            _userManager = userManager;
            _activityRepository = activityRepository;
            _leaveRequestRepository = leaveRequestRepository;
            _attendanceReportRepository = attendanceReportRepository;
            _userRepository = userRepository;
            _leaveBalanceConfigRepository = leaveBalanceConfigRepository;
            _timiosStaffRepository = timiosStaffRepository;
        }

        public ActionResult Index()
        {

            _leaveRequestRepository.SyncLeaveApp();

            var all_log = _attendanceReportRepository.GetAttendanceLog().ToList();


            ViewData["Absent"] = _attendanceReportRepository.query_status("Absent", all_log);
            ViewData["Medical Leave"] = _attendanceReportRepository.query_status("Medical Leave", all_log);
            ViewData["Paid Leave"] = _attendanceReportRepository.query_status("Paid Leave", all_log);
            ViewData["Unpaid Leave"] = _attendanceReportRepository.query_status("Unpaid Leave", all_log);
            ViewData["Others"] = _attendanceReportRepository.query_status("Others", all_log);
            ViewData["Maternity/Paternity Leave"] = _attendanceReportRepository.query_status("Maternity/Paternity", all_log);
            ViewData["Childcare Leave"] = _attendanceReportRepository.query_status("Childcare", all_log);
            ViewData["Annual Leave"] = _attendanceReportRepository.query_status("Annual Leave", all_log);

            ViewBag.Statuses = _attendanceReportRepository.status_list();
            ViewBag.Names = _attendanceReportRepository.getnamelist();

            return View(all_log);
        }

        //getting chart for everyone only accessible by administrator
        //[ActionName("Detail")]
        //[RequireHttps]
        //public ActionResult Detail()
        //{
        //    int year;
        //    string status;
        //    List<AttendanceReport> all_log = _attendanceReportRepository.GetAttendanceLog().ToList();
        //    string month = string.Empty;
        //    string team_name = Request.Form["Team"];



        //    if (String.IsNullOrEmpty(Request.Form["month"]) || Request.Form["month"] == "")
        //    {
        //        month = "Jan";
        //    }
        //    else
        //    {
        //        month = Request.Form["month"];
        //    }
        //    if (String.IsNullOrEmpty(Request.Form["Status"]) && Request.Form["Status"] != "")
        //    {
        //        status = Request.Form["Status"];

        //    }
        //    else
        //    {
        //        status = "Absent";

        //    }

        //    if (String.IsNullOrEmpty(Request.Form["year"]) || Request.Form["year"] == "")
        //    {
        //        year = DateTime.Now.Year;
        //    }
        //    else
        //    {
        //        year = Convert.ToInt32(Request.Form["year"]);
        //    }


        //Count for all log  from today back to 30 days ago
        //all_log = all_log.Where(s => s.Timestamp.ToString("MMM") == month).ToList();
        //all_log = all_log.Where(s => s.Timestamp.Year == year).ToList();
        //if (String.IsNullOrEmpty(Request.Form["Team"]) && Request.Form["Team"] != "")
        //{
        //    all_log = Team_Utility.team_query(all_log, Request.Form["Team"]);
        //}

        //if (Team_Utility.check_team_leader(User.Identity.Name))
        //{
        //    //all_log = Attendance_Utility.team_report(all_log, User.Identity.Name);
        //    team_name = Team_Utility.get_team_by_lead_email(User.Identity.Name);
        //}


        //List<ChartData> all_chart = AttendanceReport.GetChartDatas(all_log, team_name, status);
        //ViewBag.DataPoints = all_chart;
        //ViewData["month"] = month;
        //ViewData["Team"] = Request.Form["Team"];
        //    return View();
        //}


        [HttpGet]
        public ActionResult Edit(int id = 0)
        {

            AttendanceReport update_log = _attendanceReportRepository.GetSingleById(id);


            return View(update_log);
        }

        [HttpPost]
        public ActionResult MakeChanges()
        {
            _attendanceReportRepository.Update(int.Parse(Request.Form["ID"]), Request.Form["Name"], Request.Form["DeviceName"], Request.Form["Status"], Request.Form["Timestamp"], Request.Form["Remark"]);

            var currentUser = this.User;
            var currentUserId = _userManager.GetUserId(currentUser);
            Activity activity = new Activity()
            {
                ApplicationUser = _userRepository.GetSingleById(currentUserId),
                Icon = "fas fa-bed",
                CreatedAt = DateTime.Now,
                Content = "Update attendance",
            };
            _activityRepository.Add(activity);
            // List <Attendance_report> all_log = DB.Attendance_reports.Where(a => a.ID == Convert.ToInt32(Request.Form["ID"]) && a.Status == "Absent").ToList();
            return RedirectToAction("Index", new { name = Request.Form["Name"] });
        }

    }
}

Timesheet/Views/Attend/Edit.cshtml
@model Timesheet.Data.AttendanceReport
@{
    ViewData["Title"] = "Edit";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<div class="section-header">
    <h1>Edit Attendance</h1>
    <div class="section-header-breadcrumb">
        <div class="breadcrumb-item active"><a href="#">Home</a></div>
        <div class="breadcrumb-item"><a>Attendance</a></div>
        <div class="breadcrumb-item"><a>Edit</a></div>
    </div>
</div>

<div class="section-body">
    <h2 class="section-title">
        <a href="/Attend/" class="btn btn-primary">
            Back
        </a>
    </h2>

    <div class="row">
        <div class="col-lg-7 col-md-12 col-sm-12 px-5">
            <div class="card card-info">
                <div class="card-header">
                    <h4>Attendance Report</h4>
                    <div class="card-header-action">
                        <a data-collapse="#summary-container" class="btn btn-icon btn-info" href="#"><i class="fas fa-minus"></i></a>
                    </div>
                </div>
                <div class="collapse show" id="summary-container">
                    <div class="card-body row w-100">
                        @using (Html.BeginForm("MakeChanges", "Attend", FormMethod.Post, new { @class = "w-100"}))
                        {
                            @Html.AntiForgeryToken()

                            <div>

                                @Html.ValidationSummary(true, "", new { @class = "text-danger" })
                                @Html.HiddenFor(model => model.Id)

                                @Html.ValidationSummary(true, "", new { @class = "text-danger" })
                                @Html.HiddenFor(model => model.PersonnelId)

                                @*@Html.ValidationSummary(true, "", new { @class = "text-danger" })
                                    @Html.HiddenFor(model => model.Name)*@
                                <div class="form-group col-lg-12 col-12">
                                    @Html.LabelFor(model => model.Name, htmlAttributes: new { @class = "" })
                                    @*<input type="text"id="Name" name="Name" value="@Model.Name" />*@
                                    @Html.EditorFor(model => model.Name, new { htmlAttributes = new { @class = "form-control", @readonly = "readonly" } })
                                    @Html.ValidationMessageFor(model => model.Name, "", new { @class = "text-danger" })
                                    @Html.HiddenFor(model => model.Name)
                                </div>
                                <div class="form-group col-lg-12 col-12">
                                    @Html.LabelFor(model => model.DeviceName, htmlAttributes: new { @class = "" })
                                    @Html.EditorFor(model => model.DeviceName, new { htmlAttributes = new { @class = "form-control" } })
                                    @Html.ValidationMessageFor(model => model.DeviceName, "", new { @class = "text-danger" })
                                </div>

                                <div class="form-group col-lg-12 col-12">
                                    @Html.LabelFor(model => model.VerifyType)
                                    @Html.EditorFor(model => model.VerifyType, new { htmlAttributes = new { @class = "form-control" } })
                                    @Html.ValidationMessageFor(model => model.VerifyType, "", new { @class = "text-danger" })
                                </div>

                                <div class="form-group col-lg-12 col-12">
                                    @Html.LabelFor(model => model.Status)<br />
                                    @*@Html.EditorFor(model => model.Status, new { htmlAttributes = new { @class = "form-control" } })*@
                                    @Html.DropDownListFor(model => model.Status, new SelectList(new string[] { "Annual Leave", "Unpaid Leave", "Medical Leave", "Absent", "Others", "Maternity/Paternity/Childcare Leave" }, Model.Status), 
                                                           new {  @class = "form-control" })
                                    @Html.ValidationMessageFor(model => model.Status, "", new { @class = "text-danger" })
                                </div>
                                <div class="form-group col-lg-12 col-12">
                                    @Html.LabelFor(model => model.Timestamp.Date)
                                    <input class="form-control" type="text" readonly value="@Convert.ToDateTime(Model.Timestamp).ToString("dd/MM/yyyy")"/>
                                </div>

                                @Html.ValidationSummary(true, "", new { @class = "text-danger" })
                                @Html.HiddenFor(model => model.Timestamp)

                                <div class="form-group col-lg-12 col-12">
                                    @Html.LabelFor(model => model.Remark)
                                    @Html.EditorFor(model => model.Remark, new { htmlAttributes = new { @class = "form-control" } })
                                    @Html.ValidationMessageFor(model => model.Remark, "", new { @class = "text-danger" })
                                </div>

                                <div class="form-group col-lg-12 col-12" style="text-align: right">
                                    <input type="submit" id="Submit" value="Change" name="Submit" class="btn btn-info" />
                                </div>
                            </div>
                        }
                    </div>
                </div>
            </div>
        </div>


    </div>
</div>

Timesheet/Views/Attend/Index.cshtml
@model List<Timesheet.Data.AttendanceReport>
@{
    ViewData["Title"] = "Index";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<div class="section-header">
    <h1>Attendance</h1>
    <div class="section-header-breadcrumb">
        <div class="breadcrumb-item active"><a href="#">Home</a></div>
        <div class="breadcrumb-item"><a>Attendance</a></div>
    </div>
</div>

<div class="section-body">
    <h2 class="section-title">
        <button class="btn btn-primary">
            Attendance
        </button>
    </h2>

    <div class="row">
        <div class="col-lg-7 col-md-12 col-sm-12 px-5">
            <div class="card card-info">
                <div class="card-header">
                    <h4>Summary</h4>
                    <div class="card-header-action">
                        <a data-collapse="#summary-container" class="btn btn-icon btn-info" href="#"><i class="fas fa-minus"></i></a>
                    </div>
                </div>
                <div class="collapse show" id="summary-container">
                    <div class="card-body row">
                        <table class="table">
                            <tr>
                                <th>Type</th>
                                <th>Count</th>
                            </tr>
                            <tr>
                                <td>NUMBER OF Absent</td>
                                <td>@ViewData["Absent"]</td>
                            </tr>
                            <tr>
                                <td>NUMBER OF Medical Leave</td>
                                <td>@ViewData["Medical Leave"]</td>
                            </tr>
                            <tr>
                                <td>NUMBER OF Paid Leave</td>
                                <td>@ViewData["Paid Leave"]</td>
                            </tr>
                            <tr>
                                <td>NUMBER OF Others</td>
                                <td>@ViewData["Others"]</td>
                            </tr>
                            <tr>
                                <td>NUMBER OF Maternity/Paternity Leave</td>
                                <td>@ViewData["Maternity/Paternity Leave"]</td>
                            </tr>
                            <tr>
                                <td>NUMBER OF Childcare Leave</td>
                                <td>@ViewData["Childcare Leave"]</td>
                            </tr>
                            <tr>
                                <td>NUMBER OF Annual Leave</td>
                                <td>@ViewData["Annual Leave"]</td>
                            </tr>

                        </table>

                    </div>
                </div>
            </div>
        </div>

        <div class="col-lg-12 col-md-12 col-sm-12 px-5">
            <div class="card card-danger">
                <div class="card-header">
                    <h4>Attendance Table</h4>
                </div>
                <div class="collapse show">
                    <div class="card-body row">
                        <div class="table-responsive">
                            <table id="attendance-table" class="table table-striped table-bordered" style="width:100%">
                                <thead>
                                    <tr>
                                        <th> Name </th>
                                        <th> VerifyType</th>
                                        <th> Status</th>
                                        <th> Date</th>
                                        <th> Day</th>
                                        @if (User.IsInRole("admin"))
                                        {
                                            <th> Remarks</th>
                                            <th> Changes</th>
                                            <th> History_Status</th>
                                        }
                                    </tr>
                                </thead>
                                <tbody>
                                    @foreach (var item in Model)
                                    {
                                        <tr>
                                            <td>
                                                @Html.DisplayFor(modelItem => item.Name)
                                            </td>
                                            <td>
                                                @Html.DisplayFor(modelItem => item.VerifyType)
                                            </td>
                                            <td>
                                                @Html.DisplayFor(modelItem => item.Status)
                                            </td>
                                            <td>
                                                @Convert.ToDateTime(item.Timestamp).ToString("dd-MMM-yyyy")
                                            </td>
                                            <td>
                                                @Convert.ToDateTime(item.Timestamp).ToString("dddd")
                                            </td>
                                            @if (User.IsInRole("admin"))
                                            {
                                                <td>
                                                    @Html.DisplayFor(modelItem => item.Remark)
                                                </td>
                                                <td>
                                                    <a href="@Url.Action("Edit", "Attend", new { id = item.Id }, null)">
                                                        Edit
                                                    </a>
                                                </td>
                                                <td>
                                                    @Html.DisplayFor(modelItem => item.HistStatus)
                                                </td>
                                            }
                                        </tr>
                                    }
                                </tbody>
                            </table>
                        </div>
                    </div>
                </div>
            </div>
        </div>

    </div>
</div>

@section scripts{
    <script>
        $(document).ready(function () {
            $('#attendance-table').DataTable();
        })
    </script>

}